In [1]:
print('Hello')

Hello


In [2]:
class create_stack:
    def __init__(self):
        self.stack = []

    def push(self,d):
        self.stack.append(d)

    def pop(self):
        t=self.stack[-1]
        self.stack = self.stack[:-1]
        return t


In [5]:
def EvaluateExpression(exp):
    opt = ['+','-','*','/','**']
    stk = create_stack()
    L=exp.split('')

    for i in L:
        if i not in opt:
            stk.push(i)
        else:
            b=stk.pop()
            a=stk.pop()

            res = eval(a+i+b)

            stk.push(str(res))
        return stk.pop()


In [ ]:
EvaluateExpression([2, 3 ,1])



In [11]:
def reverse(root):
    if root.isEmpty():
        return root

    temp = root
    prev = None

    while(temp):
        next, temp.next = temp.next, prev 
        prev, temp = temp ,next

    return prev

In [ ]:
reverse(12)

In [13]:
n=2
res = [False for i in range(n)]
print(res)

[False, False]


In [17]:
from collections import deque
class myQueue:
    def __init__(self):
        self.Q = deque()

    def deQueues(self):
        return self.Q.popleft()
    
    def enQueue(self, x):
        return self.Q.append(x)

    def isEmpty(self):
        return False if self.Q.empty() else True


def findConnectionLevel(n, Gmat, Px, Py):
    q = myQueue()

    visited = [False for i in range(n)]
    q.enQueue(Px)
    q.enQueue(-1) 

    visited[Px]  = True

    level  =1

    while not q.isEmpty():
        v = q.deQueues()

        if v == -1:
            level +=1
            if (not q.isEmpty()):
                q.enQueue(-1)
                continue

            for i in range(n):
                if( i==Px and Gmat[v][i] == 1):
                    return level
                
                if (Gmat[v][i] and not visited[i]):
                    q.enQueue(i)
                    visited[i] = True
            return 0
            


In [ ]:
def neighbours(Amat,v):
    (rows,cols) = (len(Amat),len(Amat[0]))
    nbrs = []
    for i in range(cols):
        if Amat[i][v] == 1:
            nbrs.append(i)
    return nbrs
    
def findConnectionLevel(v,Amat, X, Y):
    level = {}
    (rows,cols) = (len(Amat),len(Amat[0]))
    for i in range(rows):
        level[i] = -1
    q = []
    q.append(X)
    level[X] = 0
    
    while q != []:
        j = q.pop()
        for k in neighbours(Amat,j):
            
            if k == Y:
                level[k] = level[j]+1
                break
            
            if level[k] == -1:
                level[k] = level[j]+1
                q.append(k)
            
    
    if level[Y] >= 0:
        return level[Y]
    else:
        return 0
vertices = int(input())
Amat = []
for i in range(vertices):
  row = [int(item) for item in input().split(" ")]
  Amat.append(row)
personX = int(input())
personY = int(input())
print(findConnectionLevel(vertices, Amat, personX, personY))

In [20]:
a = list()

print(a)


[]


In [21]:
b = dict()

print(b)


{}


In [ ]:
def FiberLink(distance_map):
    (edges, components, t, l, s) = (list() , dict(), list(distance_map.keys()), 0)
    for u in l: 
        edges.extend((d,u,v) for (v,d) in distance_map[u])
        components[u] = u
    edges.sort()

    for [d,u,v] in edges:
        if (components[u] != components[v]):
            t.append((u,v))
            c = components[u]
            s+=d

            for i in l: 
                if components[i] == c:
                    components[i] = components[v]
    return s

size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))
print(FiberLink(WL))


In [27]:
def kruskal(WList):
    (edges,component,TE)=([],{},[])
    for u in WList.keys():
        edges.extend([(d,u,v) for (v,d) in WList[u]])
        component[u] = u
    edges.sort()
    for (d,u,v) in edges:
        if component[u] != component[v]:
            TE.append((u,v))
            c = component[u]
        for w in WList.keys():
            if component[w] == c:
                component[w] = component[v]
    return(TE)

def FiberLink(distance_map):
    R = kruskal(distance_map)
    S = 0
    for e in R:
        for ed in distance_map[e[0]]:
            if ed[0]==e[1]:
                S += ed[1]
    return S
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))
print(FiberLink(WL))

10


In [26]:
com = {}
com[0] = 2
print(com)

{0: 2}


In [28]:
dedges = [(0,1,10),(0,2,80),(1,2,6),(1,4,20),(2,3,70),(4,5,50),(4,6,5),(5,6,10)]
size = 7

import numpy as np

q = np.zeros(shape=(size, size,2))
for i,j, w in dedges:
    q[i,j, 0] = 1
    q[i,j, 1] = w
print(q)

[[[ 0.  0.]
  [ 1. 10.]
  [ 1. 80.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 1.  6.]
  [ 0.  0.]
  [ 1. 20.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 70.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 50.]
  [ 1.  5.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 10.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


In [52]:
def dijkstra(WMat, s):
    # extract rows, cols and weight column
    rows, cols, x = WMat.shape
    # assigning biggest number as infinity
    infinity = np.max(WMat) * rows +1
    # dict for visited and distance
    visited, distance = {},{}

    # marking all the vertex as not visted and infinite distance
    for v in range(rows):
        visited[v] , distance[v] = False, infinity

    # DISTACE = 0
    distance[s] = 0

    # iterating through all the vertices and picking the not visited vertex with least weight 
    for u in range(rows):
        # nextd is the least weight of not visited vertex
        nextd = min(distance[v] for v in range(rows) if not visited[v])
        # nextvlist id the the vertex with nextd distance
        nextvlist = [v for v in range(rows) if (not visited[v]) and distance[v] == nextd]

        if (nextvlist == []):
            break

        # nextv is the smallest vertex which we are visiting and marking it True
        nextv = min(nextvlist)
        visited[nextv] = True
        

        for v in range(cols):
            if WMat[nextv, v, 0] == 1 and not visited[v]:
                distance[v] = min(distance[v], distance[nextv]+WMat[nextv, v,1])
    return(distance)

In [53]:
dedges = [(0,1,10),(0,2,80),(1,2,6),(1,4,20),(2,3,70),(4,5,50),(4,6,5),(5,6,10)]
size = 7
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in dedges:
    W[i,j,0] = 1
    W[i,j,1] = w
print(dijkstra(W,0))

{0: 0, 1: 10.0, 2: 16.0, 3: 86.0, 4: 30.0, 5: 80.0, 6: 35.0}


In [64]:
def bellmanford(WMat, s):
    # extract the nop of rows and cols from the matrix
    rows, cols,x = WMat.shape
    infinity = 1 + np.max(WMat) * rows
    distance={}

    # mark all the vertexes as infinity distance
    for v in range(rows):
        distance[v] = infinity

    # initialise distance to 0
    distance[s] = 0


    for i in  range(rows):
        # i for running the loop combinations n-1 times
        for u in range(rows):
            for v in range(cols):
                # u and v are the row & col for the iteraion combinations
                # i is the total number oi
                if WMat[u,v, 0] == 1:
                    distance[v] = min(distance[v], distance[u]+ WMat[u,v,1])

    return(distance)

In [63]:
edges = [(0,1,10),(0,7,8),(1,5,2),(2,1,1),(2,3,1),(3,4,3),(4,5,-1),(5,2,-2),(6,1,-4),(6,5,-1),(7,6,1)]
size = 8
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w    
print(bellmanford(W,0))

{0: 0, 1: 10.0, 2: 10.0, 3: 81.0, 4: 81.0, 5: 12.0, 6: 9.0, 7: 8.0}


Flyod marshall is a dynamic programming method 

In [71]:
def floydwarshall(WMat):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows*rows+1
   
    SP = np.zeros(shape=(rows,cols,cols+1))
    for i in range(rows):
        for j in range(cols):
            SP[i,j,0] = infinity
            
    for i in range(rows):
        for j in range(cols):
            if WMat[i,j,0] == 1:
                SP[i,j,0] = WMat[i,j,1]

    for k in range(1,cols+1):
        for i in range(rows):
            for j in range(cols):
                SP[i,j,k] = min(SP[i,j,k-1],SP[i,k-1,k-1]+SP[k-1,j,k-1])
    
    return(SP[:,:,cols])

In [72]:
edges = [(0,1,10),(0,7,8),(1,5,2),(2,1,1),(2,3,1),(3,4,3),(4,5,-1),(5,2,-2),(6,1,-4),(6,5,-1),(7,6,1)]
size = 8
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w    
    print(floydwarshall(W))

[[641.  10. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]]
[[641.  10. 641. 641. 641. 641. 641.   8.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]]
[[641.  10. 641. 641. 641.  12. 641.   8.]
 [641. 641. 641. 641. 641.   2. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 641. 641. 641. 641. 641. 641. 641.]
 [641. 64

In [91]:
def primlist(WList): 
    infinity = 1+ max([d for u in WList.keys()  for (v,d) in WList[u]])
    visited, distance = {}, {}

    # assigning flase and infinity dis
    for v in WList.keys():
        visited[v], distance[v] = False, infinity

    # final return list
    TreeEdges = []
    visited[0] = True

    # assigning dist to the respective vertices
    for v,d in WList[0]:
        distance[v] = d
    
    # 
    for i in WList.keys():
        mindist = infinity
        nextv = None

        for u in WList.keys():
            for v,d in WList[u]:
                if visited[u] and (not visited[v]) and d < mindist:
                    mindist = d
                    nextv = v
                    nexte = (u,v)

        if nextv is None:
            break

        visited[nextv] = True
        TreeEdges.append(nexte)

    # if the vertex is not visited the distance is taken to be of the min
    # value of the distance of v or the d from the vertex 
        for v,d in WList[nextv]:
            if not visited[v]:
                distance[v] = min(distance[v], d)

    return TreeEdges

In [92]:
dedges = [(0,1,10),(0,3,18),(1,2,20),(1,3,6),(2,4,8),(3,4,70)]
edges = dedges + [(j,i,w) for (i,j,w) in dedges]
size = 5
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))

print(primlist(WL))

[(0, 1), (1, 3), (1, 2), (2, 4)]


In [122]:
def kruskal1(WList):
    # TE is the final vertices pairs
    edges, comp, TE = [], {}, []

    # just changing the weights to be first element
    for u in WList.keys():
        edges.extend([d, u, v] for v,d in WList[u])
        comp[u] = u

    # sorting the edges by weight
    edges.sort()


    for d,u,v in edges:
        if comp[u] != comp[v]: 
            TE.append((u,v))
            c = comp[u]

            for w in WList.keys():
                if comp[w] == c:
                    comp[w] = comp[v]

    return comp 

In [123]:
dedges = [(0,1,10),(0,2,18),(1,2,6),(1,4,20),(2,3,70),(4,5,10),(4,6,10),(5,6,5)]
edges = dedges + [(j,i,w) for (i,j,w) in dedges]
size = 7
WL = {}
for i in range(size):
    WL[i] = []
for (i,j,d) in edges:
    WL[i].append((j,d))
print(kruskal1(WL))

{0: 0}
{0: 0, 1: 1}
{0: 0, 1: 1, 2: 2}
{0: 0, 1: 1, 2: 2, 3: 3}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
{0: 3, 1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3}


In [127]:
CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);

SyntaxError: invalid syntax (3777742347.py, line 1)

In [128]:
import psycopg2
import sys, os

def isPrime(x):
    if x <=1:
        return False
    
    for i in range(2,x):
        if x%i == 0:
            return False
        return True

conn = None

try:
    conn = psycopg2.connect(database=sys.argv[1], user=os.environ.get('PGUSER'),)
    curr = conn.cursor()

    curr.execute("select t.name, p.name, p.jersey_no from players p, teams t where p.team_id  = t.id order by p.name desc, t.name desc")

    while True:
        row = curr.fetchone()

        if not row:
            break

        if isPrime(row[2]):
            print(f'{row[1]}, {row[0]}')
        curr.close()

except(Exception, psycopg2.DatabaseError) as error:
    print(error)

finally:
    if conn is not None:
        conn.close()


ModuleNotFoundError: No module named 'psycopg2'

In [5]:
import math
import os
import random
import re
import sys


def seize(boats):
    # Write your code here
    res = 0
    for i in range(0,len(boats)):
        if i % 2 ==0:
            res = res+ boats[i]
            print(res)
            
    return res


In [6]:
seize([6,
2,
5,
10,
3,
2,
15])

6
11
14
29


29

In [4]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

        
row = len(arr)//2
col = len(arr[0])//2
for i in range(row+1):
    for j in range(col+1):
        val = arr[i][j]+arr[i][j+1]+arr[i][j+2]+arr[i+1][j+1]+arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2]
        print(val)
        
        if val >= res:
            res = val
        

            
print(res)
            

-6
-20
-25
-24
-22
-31
-28
-31
-25
-14
-24
-33
-20
-24
-19
-33
0


In [20]:
def Twin_Primes(n,m):
    a=[]
    res=[]
    for i in range(n,m+1):
        for j in range(2,i):
            if i%j == 0:
                break
        else:
            if i>2:
                a.append(i)

    for i in range(0,len(a)-1,2):
        res.append((a[i],a[i+1]))

    return res,a

Twin_Primes(2,10)

([(3, 5)], [3, 5, 7])

In [1]:
a = [1,2,3,4]

for i in range(len(a)):
    print(a[i], a[i]+2)

    # print((a[i], a[j]))

1 3
2 4
3 5
4 6


In [18]:
n = 125
a = bin(n)
binary = a[2:]
binary = str(binary)

for i in range(len(binary)):
    if binary[i] == '0':
        print(i)

5


In [5]:
# print(binary)


In [1]:
# cook your dish here
t = int(input())

for a in range(t):
    
    i = int(input()):
        
        if i < 51:
            print('LEFT')
        elif  50 < i < 101:
            print('RIGHT')

SyntaxError: invalid syntax (857925508.py, line 6)

In [6]:
def prime(n):
    lst=[]
    for i in range(1,n+1):
        if  n % i != 0 and n > 2:
            lst.append(i)
    return lst

prime(5)

[2, 3, 4]

In [14]:
n = int(input())
for i in range(1,n+1):
    for j in range(1,i+1):
        if i % j != 0 and n > 2:
            print(i)

3
4
5
5
5


In [16]:
# prime number from 1 to n

n = int(input())
for i in range(1,n+1):
    for j in range(2,i):
        if i % j == 0:
            break
    else:
        print(i)

1
2
3
5


In [1]:
def prime(n):
    if n <2:
        return False
    for i in range(2, n//2+1):
        if n%i == 0:
            return False
        return True
        
def Goldbach(n):
    res = []
    for i in range((n//2)+1):
        if prime(i) == True:
            if prime(n-i) == True:
                res.append((i, n-i))
    return res
            
n=int(input())
print(sorted(Goldbach(n)))

[(5, 11), (7, 9)]


In [5]:
def odd_one(L):
  P = {}
  for elem in L:
    if type(elem) not in P:
      P[type(elem)] = 0
    P[type(elem)] += 1
  for key, value in P.items():
    if value == 1:
      return key.__name__

In [6]:
odd_one([1, 2, 3.4])

'float'

In [ ]:
class Triangle:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def Is_valid(self):
        if self.a + self.b > self.c and self.a + self.c > self.b and self.b + self.c > self.a:
            return 'Invalid'
        else:
            return 'Valid'
    def Side_Classification(self):
        if self.Is_valid() == 'Valid':
            if self.a == self.b == self.c:
                return 'Equilateral'
            elif self.a == self.b or self.a == self.c or self.b == self.c:
                return 'Isosceles'
            else:
                return 'Scalene'

    def Angle_Classification(self):
            if self.Is_valid() == 'Valid':
                if self.a**2 + self.b**2 == self.c**2 or self.a**2 + self.c**2 == self.b**2 or self.b**2 + self.c**2 == self.a**2:
                    return 'Right'
                elif self.a**2 + self.b**2 > self.c**2 or self.a**2 + self.c**2 > self.b**2 or self.b**2 + self.c**2 > self.a**2:
                    return 'Acute'
                else:
                    return 'Obtuse'
            else:
                return 'Invalid'
    def Area(self):
        if self.Is_valid() == 'Valid':
            s = (self.a + self.b + self.c)/2
            return (s*(s-self.a)*(s-self.b)*(s-self.c))**0.5
        else:
            return 'Invalid'

In [ ]:
def binarySearchIndexAndComparisons(L, k):
    s = len(L)
    if (s<1):
        return (False, 0)

    left = 0
    right = s-1
    count = 0
    while (left <= right):
        count += 1
        mid = (left + right)//2
        if (L[mid] == k):
            return (True, count)
        elif (L[mid] > k):
            right = mid - 1
        else:
            left = mid + 1
    return (False, count)

In [ ]:
from operator import index


def sortInRange(L, r):

    countDict = dict.fromkeys(range(r),0)
    for num in L:
        countDict[i] += 1

    index = 0
    for key in countDict.keys():
        for i in range(countDict[key]):
            L[index] = key
            index += 1


In [ ]:
def insert_end(self,data):
    newnode = Node(data)
    newnode.prev = self.last
    if self.head == None:
        self.head = newnode
        self.last = newnode
    else:
        self.last.next = newnode
        self.last = newnode
def delete_end(self):
    if(self.head != None):
        if self.head == self.last:
            self.head = None
            self.last = None
        else:
            self.last = self.last.prev
            self.last.next = None

In [ ]:
def hashfunction(self, data):
    i = 0
    key = (data % self.m + self.c1*i + self.c2*(i**2)) % self.m
    while self.hashtable(key)[key] != None and i < self.m:
        i += 1
        key = (data % self.m + self.c1*i + self.c2*(i**2)) % self.m
    return key

def store_data(self, data):
    if self.hashtable.count(None) == 0:
        key = self.hashfunction(data)
        self.hashtable[key] = data
    else:
        print('Hash table is full')

def display_hashtable(self):
    return self.hashtable

In [3]:
sumn = 0
i = 10

while i < 1:
    sum = sum + i
    sum = sum * 2
    i -=1

print(sumn)

0


In [6]:
f = lambda n:1 if n <= 1 else n * f(n-1)

g = f(4)
print(g)

24


In [7]:
def ex(arr):
    temp = 0
    for x in arr: 
        if x % 2 ==1:
            temp +=1
        else:
            temp = 0
        if temp == 3:
            return True
    return False

In [8]:
ex([4,5,7,23,12])

True

In [9]:
def a(nums):
    has_pos = False
    has_neg = False
    for num in nums:
        has_pos = num > 0
        has_neg = num < 0

    return (has_pos, has_neg)

In [10]:
a([1,-1,-2])

(False, True)

In [11]:
print(sorted(["1", "2", "15", "-7", "300"]))

['-7', '1', '15', '2', '300']


In [12]:
def find_first_position(arr, fn):
    pos  = False
    for i in range(len(arr)):
       row = arr[i]
       for j in range(len(row)):
              if fn(row[j]):
                pos = (i, j)
                break
    return pos
